### ISSUE TITLE
Please, make your readme useful

### ISSUE THREAD

**Issue by Sly-Ripper** [thephpleague/omnipay-paypal#102]
This one helps: https://github.com/clippings/omnipay-paypal

**Comment by kayladnls** [comment]
I'm definitely aware of this and working on it. I'll tag back here when I've got it finished.

**Comment by coatesap** [comment]
@greydnls - any progress (nearly) a year on? ;) 
As this is such a popular driver, a few pointers would really make life easier for developers, especially those who won't know which areas of the source to poke around in. I'm thinking the default/required configuration parameters for the driver (eg. username, password, signature, for Express), etc...

**Comment by delatbabel** [comment]
There's a fair bit of documentation now, in the PayPal_REST gateway (note that PayPal is recommending that all new accounts use the REST gateway so this is the one I've been focussing on).  If you want to commit a PR for better documentation for the legacy gateways then please go ahead but I don't have the time to go over them all myself.

**Comment by coatesap** [comment]
@delatbabel - ah, that's worth knowing about the REST gateway. Does that work for merchants *not* using a 'Pro' account ie. a direct replacement for the Express integration?

**Comment by delatbabel** [comment]
Yes I believe that it's correct that new Express customers are advised to consider REST instead. I'm not aware of any plans by PayPal to deprecate the Express gateway in favour of the REST gateway but I don't work for PayPal so I'm not party to any discussions behind the scenes there.  They certainly do encourage all new customers to use REST.
