### ISSUE TITLE
[Sandbox Testing] Exception

### ISSUE THREAD

**Issue by DanielHitchen** [thephpleague/omnipay-paypal#104]
Hi guys,

Not sure if this is something I've done wrong, or whether something has changed that I've not updated, but when testing via the Paypal Sandbox for Express Checkout, I've started getting the following error:

![exception](https://cloud.githubusercontent.com/assets/7501909/12714718/396241ea-c8ce-11e5-8d9d-77be51476dd6.jpg)

I have all the correct sandbox API credentials from my own PayPal developer test account, but for some reason its' not processing.

When I input the API settings from my live business account, everything works fine, just not the sandbox.

Here is how I'm initialising the gateway in my script:
```
$gateway = Omnipay::create( "PayPal_Express" );
$gateway->setTestMode( true );
$gateway->setUsername( 'paypal_username' );
$gateway->setPassword( 'paypal_password' );
$gateway->setSignature( 'paypal_signature' );
```

Nothing has changed in my script except for me running the odd "composer update" to pull your latest code.

Any help would be much appreciated.

**Comment by delatbabel** [comment]
PayPal have recently updated their sandbox to require TLS 1.2 in advance of pushing the same update to their production website. You may need to update your libcurl to support that.

e.g. on CenOS 1.2 you need to do this:

```
rpm -Uvh http://www.city-fan.org/ftp/contrib/yum-repo/city-fan.org-release-1-12.rhel6.noarch.rpm
yum -y install libcurl
yum -y update
```

**Comment by delatbabel** [comment]
Duplicate of #103 Note in this case your libcurl is trying to negotiate SSLv3. That has been deprecated for a very long time.

**Comment by DanielHitchen** [comment]
Thanks @delatbabel for your response - I'm testing locally via MAMP on OSX 10.10.5 and have libcurl version 7.41.0 installed, are there any workaround that you know of for my situation ie not on CentOS 6 etc?

Apologies for my ignorance on this issue.

**Comment by delatbabel** [comment]
Sorry, I can't help with MacOS. However I can see from the screen shot that it's definitely a TLS issue. You might try some MacOS forums to try to get help with that.

**Comment by DanielHitchen** [comment]
OK @delatbabel , thanks for your help anyway, I will do some searching
