### ISSUE TITLE
SSL Errors

### ISSUE THREAD

**Issue by lonnieezell** [thephpleague/omnipay-paypal#108]
It looks like PayPal changed the way their SSL works, requiring higher encryption in January. This is causing me to get the following error coming back through Guzzle: 

    [curl] 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [url] https://api-3t.sandbox.paypal.com/nvp?VERSION=119.0&USER=...

Is there a way to pass CURL-specific settings through the PayPal lib and on to Guzzle? If so, I'm missing it. I need to try setting a different version of SSL to be used by cURL but not having any luck. 

Or have you found a way around this recently?

**Comment by delatbabel** [comment]
2 things to try:

* Update your libcurl to a version > 7.40 as per #103 
* Try the patch suggested in PR #107 although I suspect that you will have to update your libcurl anyway. I have not verified that #107 works without updating libcurl, and I have not verified that it makes any difference with libcurl updated.

**Comment by lonnieezell** [comment]
Please ignore the comment over at the main OmniPay repo I just made since this one is still open.

1. libcurl is 7.43.0 so that's not the issue. 
2. Is there any way without hacking the core to get access to the httprequest? It seems to be a protected property and no accessor methods that I've seen. Hopefully I'm just missing something?

**Comment by lonnieezell** [comment]
Per our discussion on main OmniPay issues list, there is NOT a way to pass options through. Sounds like a good feature request, then. :) 

Thanks.
