### ISSUE TITLE
Error SSL23_GET_SERVER_HELLO:sslv3 alert handshake

### ISSUE THREAD

**Issue by danniejpt** [thephpleague/omnipay-paypal#110]
Hello 

Recently, I got this message when try to purchase with Paypal

Message: [curl] 35: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure [url] https://api-3t.sandbox.paypal.com/nvp?...

Anyone get the same error?

It's work good before and this may give you more information: https://www.paypal-knowledge.com/infocenter/index?page=content&id=FAQ1766&expand=true&locale=en_US

Regards

**Comment by delatbabel** [comment]
Yes, you need to update your libcurl to version > 7.40
