### ISSUE TITLE
Discontinue Use of GET Method for Classic APIs Microsite

### ISSUE THREAD

**Issue by fedeisas** [thephpleague/omnipay-paypal#112]
Hi! I just got this email from Paypal. Is there any plans to implement this (or maybe it's already implemented?). I couldn't find it in the code. Thanks!

https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1927&viewlocale=en_US

**Comment by delatbabel** [comment]
I don't have plans to implement this (I only use the REST API which is unaffected) but I will be happy to accept PRs on this.

**Comment by alex-osborn** [comment]
@fedeisas Came to check the same issue, I believe the requests are already compliant.

All requests in the Pro/Express gateway are sent via Omnipay\PayPal\Message\AbstractRequest::sendData(), which is hardcoded to POST.

https://github.com/thephpleague/omnipay-paypal/blob/3d39ab63f9c1e31893ec61bbab9eda98df5f1a6f/src/Message/AbstractRequest.php#L320
