### ISSUE TITLE
PHP7 Support for empty json response

### ISSUE THREAD

**Issue by rumeau** [thephpleague/omnipay-paypal#131]
Hello, i'm dealing with a case where a request to PayPal REST API returns an empty body response. Specifically when cancelling a subscription.

On PHP <7, this is no problem as json_decode can parse an empty string without reporting an error.

IE:

```php
$body = "";
var_dump(json_decode($body)); // NULL
var_dump(json_last_error_msg()); // No error
```

But for PHP7 this response is invalid JSON syntax.
```php
$body = "";
var_dump(json_decode($body)); // NULL
var_dump(json_last_error_msg()); // Syntax Error
```

Therefore when creating the response:

```php
return $this->response = $this->createResponse($httpResponse->json(), $httpResponse->getStatusCode());
```

$httpResponse->json() returns an exception on invalid JSON being parsed.

To solve this, i think empty response  body should not be passed through ```$httpResponse->json()``` since json_decode is doing a good job, the problem is that PayPal wont return json all the time.

Even when subscriptions are not in the scope of Omnipay, this could be happening on any other case where PayPal is responding with an empty body, including any other payment gateway that makes use of json_decode.

**Comment by delatbabel** [comment]
If you can submit a PR for this then I can merge it.

**Comment by rumeau** [comment]
PR is ready #132 

Thanks.
