### ISSUE TITLE
2.5.5 Release

### ISSUE THREAD

**Issue by mwisner** [thephpleague/omnipay-paypal#136]
Hi,

I'm just wondering if there are plans to do a 2.5.5 release? 

https://github.com/thephpleague/omnipay-paypal/compare/v2.5.4...master

There is a fix in master (https://github.com/thephpleague/omnipay-paypal/commit/488cf7f47be23139501f1d1c8a2fd8712a6693e1) that fixes the specific error (Method Specified is not Supported). We're currently running into this in production and would like to avoid using the the dev-master branch. 

(This also looks related to #130)

**Comment by delatbabel** [comment]
Done.  Normally I wait for someone to verify that it works in production, and notify this by commenting on the PR.  In this case I hadn't received confirmation.
