### ISSUE TITLE
Error Code 10486 in Paypal Express

### ISSUE THREAD

**Issue by lukeholder** [thephpleague/omnipay-paypal#143]
Full error background: https://developer.paypal.com/docs/classic/express-checkout/ht_ec_fundingfailure10486/

When returning from a redirect to paypal and submitting the `completePayment` gateway request, paypal can return error code 10486. The associated error message is "This transaction couldn't be completed. Please redirect your customer to PayPal."

Should omnipay be handling this?

I mean, should the `completePayment` error response object have a `isRedirect` set to true?

At the moment, my app would need to manually check for this error code and somehow build the same redirect url again to send the customer back to paypal, but that seems like it should be a job for the gateway driver perhaps?

Let me know if I am way off, or correct. I will then look at implementing a redirect response into the `completePayment` response object within this driver.

**Comment by mikeyc7m** [comment]
i'm still having problems with this error. i'm successfully trapping it and redirecting back to paypal, however during the redirect the payment is marked as captured and the order paid.

**Comment by lukeholder** [comment]
@mikeyc7m sounds like your app is not redirecting and updating the local order?

**Comment by mikeyc7m** [comment]
the app is redirecting - i don't return to the site and paypal displays an expected error message. but meanwhile the order is marked as paid/completed. maybe it's omnipay, or maybe it's silvershop, or maybe it's my code, or maybe this isn't fixed.
