### ISSUE TITLE
Package guzzle/guzzle is abandoned

### ISSUE THREAD

**Issue by Arwany** [thephpleague/omnipay-paypal#156]
Hi,

I searched before posting, but could not find anything related.

When I update my project using this library, I get this error:

`Package guzzle/guzzle is abandoned, you should avoid using it. Use guzzlehttp/guzzle instead.`

Any idea if there will come an update to fix this issue, or is it hard at the moment?

Thank you!

**Comment by delatbabel** [comment]
This is an FAQ. Guzzle 6+ support comes with Omnipay 3.0, introducing it now without a major version upgrade will break too many things.
