### ISSUE TITLE
PayPal discontinuing GET method 

### ISSUE THREAD

**Issue by rohitpatil-tudip** [thephpleague/omnipay-paypal#160]
We are using omnipay bundle for pay pal integration, now we got mail from PayPal that they are discontinuing GET method do we need to change the code?
for more details here is a link
 https://www.paypal-knowledge.com/infocenter/index?page=content&widgetview=true&id=FAQ1927&viewlocale=en_US

**Comment by delatbabel** [comment]
The PayPal gateways do not use the GET method.

**Comment by vishalpawar-tudip** [comment]
Hello @delatbabel 
Sorry, but we need to know our PayPal gateways use get method or if not how can we test it?
Please reply us as soon as possible.
