### ISSUE TITLE
PayPal_ExpressInContext is Deprecated

### ISSUE THREAD

**Issue by abude** [thephpleague/omnipay-paypal#162]
**Important**: This integration method is Deprecated as of January 1, 2017. For new integrations, see the PayPal Express Checkout Integration Guide.

**Source**: https://developer.paypal.com/docs/classic/express-checkout/ec_integration/

Please update.

Thanks!

**Comment by delatbabel** [comment]
A quick read through the code indicates to me that we aren't using ExpressInContext anywhere except in the specific gateway that supports it.  For current users that gateway should still work, although it's not supported for new users.  Updating the code to remove that gateway would break BC for current users, so it's not something that we'd consider doing.
