### ISSUE TITLE
Class '\Omnipay\PayPal\ExpressGateway' not found

### ISSUE THREAD

**Issue by BhagiLimbu** [thephpleague/omnipay-paypal#164]
I am new in Omnipay and testing a Paypal_Express. I follow instruction https://github.com/ignited/laravel-omnipay most of the syntax does not support (Documentation is very poor) and initialise  myself.

       $factory = new GatewayFactory();
      $factory->create('Paypal_Express'); // Error thrown from this line.

Anyone face similar experience before ?

**Comment by leith** [comment]
Typically I use the `Omnipay::create('Engine_Name');` format, but manually creating the factory should be fine as well. Are you sure it's not just that you're using `Paypal_Express` instead of `PayPal_Express` (note second uppercase 'P')?

You shouldn't really need to be manually creating the gateway instance if you're using the Laravel integration you mention, though.

**Comment by BhagiLimbu** [comment]
Thanks for quick reply, I was not sure what was cause behind the failed. When I passed correct engine name Omnipay::create('PayPal_Express'); it returns gateway. However, I need to pass all configuration information such as user id, password, signature etc. If I use laravel integration 'Ignited', it set all configuration key and value on ExpressGateway, but it does not show code intellisense. I use this way to create instance of PayPal_Express 

$oInstance = app()->make('omnipay');
$gateway = $oInstance->gateway('paypal'); // read configuration file (laravel-omnipay)

Thank you.

**Comment by leith** [comment]
Looks like this issue is better suited to discussion on the @ignited repo then (I can see you already [opened an issue](https://github.com/ignited/laravel-omnipay/issues/38) there), so this can probably get closed.

**Comment by sudiptpa** [comment]
@BhagiLimbu look at this blog post for the complete guide for omnipay/paypal [here](https://sujipthapa.co/blog/a-guide-to-integrate-omnipay-paypal-with-laravel)
