### ISSUE TITLE
CurlException on PayPal_Express driver

### ISSUE THREAD

**Issue by marlboroman3** [thephpleague/omnipay-paypal#167]
So, everything has been working well for ages when testing PayPal_Express integration on my Codeigniter development system (my localhost).  But, suddenly I start getting the following exception on send() to PayPal's sandbox environment.  I'm in test mode and have confirmed the username, password and signature (obfuscated here) are correct from developer.paypal.com.

`ERROR - 2017-07-10 02:30:13 --> Exception processing payment (key: 5962e6b5cbc20 ): Guzzle\Http\Exception\CurlException: [curl] 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054 [url] https://api-3t.sandbox.paypal.com/nvp?VERSION=85.0&USER=..........&PWD=..........&SIGNATURE=..........&METHOD=SetExpressCheckout&PAYMENTREQUEST_0_PAYMENTACTION=Authorization&PAYMENTREQUEST_0_AMT=15.20&PAYMENTREQUEST_0_CURRENCYCODE=AUD&SOLUTIONTYPE=Sole&LANDINGPAGE=Billing&RETURNURL=http%3A%2F%2Flocalhost%2Fohsewyou%2Fcart%2FpaymentReturn%2F&CANCELURL=http%3A%2F%2Flocalhost%2Fohsewyou%2Fcart%2Fcheckout&HDRIMG=&BRANDNAME=&LOGOIMG=&CARTBORDERCOLOR= in C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php:359
Stack trace:
#0 C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php(292): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php(257): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\Request), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php(240): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php(224): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMulti.php(111): Guzzle\Http\Curl\CurlMulti->perform()
#5 C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Curl\CurlMultiProxy.php(94): Guzzle\Http\Curl\CurlMulti->send()
#6 C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Client.php(284): Guzzle\Http\Curl\CurlMultiProxy->send()
#7 C:\wamp64\www\ohsewyou\vendor\guzzle\guzzle\src\Guzzle\Http\Message\Request.php(198): Guzzle\Http\Client->send(Object(Guzzle\Http\Message\Request))
#8 C:\wamp64\www\ohsewyou\vendor\omnipay\paypal\src\Message\AbstractRequest.php(316): Guzzle\Http\Message\Request->send()
#9 C:\wamp64\www\ohsewyou\vendor\omnipay\common\src\Omnipay\Common\Message\AbstractRequest.php(675): Omnipay\PayPal\Message\AbstractRequest->sendData(Array)
#10 C:\wamp64\www\ohsewyou\application\controllers\cart.php(549): Omnipay\Common\Message\AbstractRequest->send()
.
.
.
`

**Comment by angelleye** [comment]
Looks like your server must be sending HTTP requests using SSLv3 instead of TLS 1.2 which is now required by PayPal (and pretty much all web services).

For details you can see this article:  https://www.angelleye.com/paypal-ssl-error-poodle-vulnerability/

Most importantly,

>If you want to use TLS 1.2 you’ll need to upgrade to OpenSSL 1.0.1 as a minimum, and then you’ll be able to set CURLOPT_SSLVERSION to 6 (TLS 1.2).

>If you want TLS 1.2 to be used automatically during SSL requests, you’ll also need to upgrade to PHP 5.5.19+ (this is the ideal solution but many projects are still on older PHP versions).

**Comment by marlboroman3** [comment]
Doing a Composer update has solved this particular problem.

"omnipay/paypal": "~2.0"

gave me V2.6.3

**Comment by angelleye** [comment]
Sounds like your server is good but the old code was still using SSLv3.  new code must be using TLS 1.2, so it sounds like you're set.
