### ISSUE TITLE
Getting below error when trying to payment with paypal 

### ISSUE THREAD

**Issue by naveentyagi001** [thephpleague/omnipay-paypal#168]
Getting below error when trying to payment with paypal 

CurlException in CurlMulti.php line 359: [curl] 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 104 [url] https://api-3t.sandbox.paypal.com/nvp?VERSION=119.0&USER=demo1_api1.demoe3.com&PWD=1399456057&SIGNATURE=AFcWxV21C7fd0v3bYYYRCpSSRl31AM1OM-eY.gDnmCtvOt3OMiTPFLnd&METHOD=SetExpressCheckout&PAYMENTREQUEST_0_PAYMENTACTION=Authorization&PAYMENTREQUEST_0_AMT=27.22&PAYMENTREQUEST_0_CURRENCYCODE=USD&PAYMENTREQUEST_0_DESC=feature%20add%20payment&SOLUTIONTYPE=Sole&LANDINGPAGE=Billing&RETURNURL=http%3A%2F%2Fmotors.dev.gipl.inet%2Fdev%2Fsave-order&CANCELURL=http%3A%2F%2Fmotors.dev.gipl.inet%2Fdev%2Fad-post&HDRIMG=&BRANDNAME=&LOGOIMG=&CARTBORDERCOLOR=

**Comment by angelleye** [comment]
You need to make sure your server is sending http requests via TLS 1.2 and not SSLv3.  

* https://www.angelleye.com/paypal-ssl-error-poodle-vulnerability/

> If you want to use TLS 1.2 you’ll need to upgrade to OpenSSL 1.0.1 as a minimum, and then you’ll be able to set CURLOPT_SSLVERSION to 6 (TLS 1.2).
> 
> If you want TLS 1.2 to be used automatically during SSL requests, you’ll also need to upgrade to PHP 5.5.19+ (this is the ideal solution but many projects are still on older PHP versions).
