### ISSUE TITLE
Documentation for completePayment is incorrect

### ISSUE THREAD

**Issue by asmecher** [thephpleague/omnipay-paypal#172]
In https://github.com/thephpleague/omnipay-paypal/blob/master/src/Message/RestCompletePurchaseRequest.php#L26..L43, some request variables are fetched...

    $paymentId = $_GET['paymentId'];
    $payerId = $_GET['payerId'];

...but then other variables are used in the `completePurchase` call...

    $transaction = $gateway->completePurchase(array(
        'payer_id'             => $payer_id,
        'transactionReference' => $sale_id,
    ));

I think `$sale_id` should be `$paymentId`, and `$payer_id` should be `$payerId`. For bonus points, it would be nice for `transactionReference` and `paymentId` to be reconciled, but I suppose that would need deeper changes.

**Comment by chrisatomix** [comment]
This one caught me out just now, hopefully the PR gets merged soon.
