### ISSUE TITLE
ExpressAuthorizeRequest and ExpressCompleteAuthorizeRequest

### ISSUE THREAD

**Issue by MarlonEtiene** [thephpleague/omnipay-paypal#176]
Hello,

In my country we can configure credit cards to have installments, but to show this the parameter `PAYMENTREQUEST_0_PAYMENTACTION` need to have value `Sale`, but in the both classes it is `Authorization`.

My question is if have any way to change this value from `Authorization` to `Sale`?

Thank's in advance

**Comment by nitemarket** [comment]
@MarlonEtiene you can use `ExpressCompletePurchaseRequest`, its `PAYMENTREQUEST_0_PAYMENTACTION` is set to `Sale`.

**Comment by MarlonEtiene** [comment]
@nitemarket Thank you for your response, I'll go try your solution.
Sorry for delay to response, I was with big troubles.

Again thank you!
