### ISSUE TITLE
Class 'Omnipay\Tests\GatewayTestCase' not found

### ISSUE THREAD

**Issue by islamdarwish** [thephpleague/omnipay-paypal#181]
I want to contribute to this package to add a feature i want to be there and i want to make unittest for it but when i run "phpunit" it gives me this error:
PHP Fatal error:  Class 'Omnipay\Tests\GatewayTestCase' not found in /var/www/html/omnipay-paypal/tests/ExpressGatewayTest.php on line 7

Thanks

**Comment by leith** [comment]
@islamdarwish sounds like you did your `composer install` with the `--no-dev` option turned on, which would exclude the Omnipay test classes. Running it without should install the `require-dev` section and let you run the tests.

**Comment by islamdarwish** [comment]
Thanks alot for help, but is not the case it seems that it was a problem in the internet connection so that some files is not downloaded and when i `composer install` again, it downloaded the rest of files.
