### ISSUE TITLE
No api for updating and retrieving the list cards

### ISSUE THREAD

**Issue by renielDev** [thephpleague/omnipay-paypal#190]
There is an option for adding cards but, none for updating and retrieving vaulted cards.

**Comment by delatbabel** [comment]
I think that generically, in Omnipay, there is no method to retrieve card data -- doing so would probably break PCI requirements.  Similarly there is no generic method to update card data -- normally this is done via a card delete / card add.  The majority of gateways that support stored card data do not support updating or retrieving that card data.
