### ISSUE TITLE
PayPal discontinuing GET method 

### ISSUE THREAD

**Issue by vishalpawar-tudip** [thephpleague/omnipay-paypal#191]
Hello Team,

We are using omnipay for PayPal integration. Now we have got an email from Paypal for discontinuing use GET method. So, do we need to change the code if not how do we can test it?

We are using omnipay-PayPal version: "v2.5.1".
Here is the link https://www.paypal.com/au/webapps/mpp/discontinuation-get-method

**Comment by SlimDeluxe** [comment]
2.5.4 release note:

> Incorporates changes to make POST requests for the classic APIs instead of GET requests. This is required by 18th June 2016.

So I guess just update your library.

**Comment by vishalpawar-tudip** [comment]
Thanks, @SlimDeluxe .
Can you please provide the link to 2.5.4 release note?

**Comment by SlimDeluxe** [comment]
https://github.com/thephpleague/omnipay-paypal/releases/tag/v2.5.4

**Comment by vishalpawar-tudip** [comment]
Thanks, @SlimDeluxe.
It would be really helpful.
