### ISSUE TITLE
Laravel 5.6 issue

### ISSUE THREAD

**Issue by TheTechnoMan** [thephpleague/omnipay-paypal#199]
Hello, 

I am unable to install the package on Laravel 5.6.

See: https://pastebin.com/2ckfA13D

**Comment by vdbelt** [comment]
v3 was just released and supports L5.6. If you try again, it should work.

**Comment by TheTechnoMan** [comment]
My bad, I now require 3.*. But new issue:

  Problem 1
    - omnipay/paypal v3.0.0 requires omnipay/common ^3 -> satisfiable by omnipay/common[v3.0.0, v3.0.1, v3.0.2].
    - omnipay/paypal v3.0.1 requires omnipay/common ^3 -> satisfiable by omnipay/common[v3.0.0, v3.0.1, v3.0.2].
    - omnipay/paypal v3.0.2 requires omnipay/common ^3 -> satisfiable by omnipay/common[v3.0.0, v3.0.1, v3.0.2].
    - omnipay/common v3.0.2 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0.1 requires php-http/client-implementation ^1 -> no matching package found.
    - omnipay/common v3.0.0 requires php-http/client-implementation ^1 -> no matching package found.
    - Installation request for omnipay/paypal 3.* -> satisfiable by omnipay/paypal[v3.0.0, v3.0.1, v3.0.2].

**Comment by judgej** [comment]
That's fine. You now need to install a later version of Guzzle (or an equivalent) yourself. Omnipay will use any one of half a dozen that your application may happen to be using, and this error means your application is not using any yet. Try Guzzle v6 (I think) or just the latest that will install.

**Comment by TheTechnoMan** [comment]
Ah, I see. Thanks, now it is working :)

**Comment by judgej** [comment]
Bleeding edge! We need people like you to lead the rest. Thanks for giving it a go. If there is anything that you think may help the next person installing, just add it to this ticket and I'll aim to get it into the documentation, or do a PR on the omnnipay-common docs. Every bit makes it smoother for the next person.
