### ISSUE TITLE
PayPal_Rest (Paypal Rest API) 是否缺少  /payments/payouts  的路由请求方案

### ISSUE THREAD

**Issue by ShaoZeMing** [thephpleague/omnipay-paypal#205]
您好，很高心使用你的工具包。但目前我遇到一个问题：我在使用Paypal Rest API  执行调用Create payouts    POST/v1/payments/payouts

代码：
  $data = [
            "sender_batch_header" => [
                "sender_batch_id" => time(),
                "email_subject" => "You have a payment",
                "email_message" => "You have received a payout! Thanks for using our service!",
            ],
            "items" => [
                [
                    "recipient_type" => "EMAIL",
                    "amount" => [
                        "value" => 200.00,
                        "currency" => "USD"
                    ],
                    "receiver" => "szm19920426-buyer@gmail.com",
                    "note" => "Thank you.",
                ]
            ],
        ];
$response = $gateway->purchase()->sendData($data);

发现路由默认请求的是  return parent::getEndpoint() . '/payments/payment';  
没有找到 return parent::getEndpoint() . /payments/payouts，
想请问一下，是我操作失误，还是这个工具包没有包含付款这个功能？

**Comment by barryvdh** [comment]
Sorry, I don't understand this request.

**Comment by ShaoZeMing** [comment]
thank you.
