### ISSUE TITLE
Smart Payment Buttons support?

### ISSUE THREAD

**Issue by fangyuqiang** [thephpleague/omnipay-paypal#248]
now i just want set the paypal's smart payment buttons in my site, but i found it seem that omnipay-paypal didn't implement the Order API, so does it mean omnipay-paypal didn't support the smart payment buttons? or do i make some mistake about this?
if i need this feature, it's there some advise about how to do this ?

https://developer.paypal.com/docs/checkout/

**Comment by Pushkraj19** [comment]
rip this repo

**Comment by delatbabel** [comment]
> rip this repo

thanks for your useful and informative contribution to the code.
