### ISSUE TITLE
Cannot pass token and PayerID to completePurchase

### ISSUE THREAD

**Issue by altmind** [thephpleague/omnipay-paypal#34]
I have a REST JSON api and I need to charge user in 2 steps(purchase->completePurchase). I got `purchase` call return token and PayerID, now I'm trying to do `completePurchase`
```
$paypal_token = $this->input->post('paypal_token');
$paypal_payerid = $this->input->post('paypal_payerid');

$request = $this->paypalGateway->completePurchase(
            array(
                'token' => $paypal_token,
                'payerid' => $paypal_payerid,
                'amount' => $total,
                'currency' => 'USD',
            )
        );
```

This issues invalid request to paypal without token and payerid. In fact, if you look in `omnipay/paypal/src/Message/ExpressCompleteAuthorizeRequest.php`, line 22, you can see
```
        $data['TOKEN'] = $this->httpRequest->query->get('token');
        $data['PAYERID'] = $this->httpRequest->query->get('PayerID');
```
This is horribly wrong. Even if we pass params manually in completePurchase, they got clobbered by values from GET params and there is no chance to disable this behavior.

I suggest:
* Remove implicit use of page get params(Not only PHP can work as CLI, PHP can also get params from JSON POST, so its unclear why library is so opinionated about where params should be)
* Add ability to pass token and PayerID in params. They should not be clobbered or overwritten.
* Add method `setPayerId` to `ExpressCompleteAuthorizeRequest` to setPayerId to existing request. Currently, you can do `setToken` on request, but no `setPayerId`

**Comment by notrix** [comment]
:+1:
