### ISSUE TITLE
How to Set up a Reference Transaction ?

### ISSUE THREAD

**Issue by Vazgen7788** [thephpleague/omnipay-paypal#37]
How to Set up a Reference Transaction

**Comment by kayladnls** [comment]
I'm sorry, I'm not sure I understand the question? What is it you're trying to do?

**Comment by Vazgen7788** [comment]
I want Use PayPal Express for Capture Future Payments here is paypal documentation (https://developer.paypal.com/docs/classic/express-checkout/ht_ec-refTrans-SetEC-DoRefTrans-curl-etc/) but i can't find any method in omnipay which alows it.
