### ISSUE TITLE
RestUpdateCardRequest does not work

### ISSUE THREAD

**Issue by delatbabel** [thephpleague/omnipay-paypal#41]
RestUpdateCardRequest does not work in its current format.  The issues are several:

* The class extends RestCreateCardRequest but the endpoint in getEndpoint is defined as parent::getEndpoint() . '/vault/credit-card/' . $this->getCardReference(). This results in a nonsense URL like /vault/credit-card/vault/credit-card/<card-id> which just returns a 404 error on the gateway.

* The format of parameters for update card is somewhat different to the format for create card, and so the getData function inherited from RestCreateCardRequest does not produce a format that is correct for update card.  See https://developer.paypal.com/docs/api/#update-a-stored-credit-card

**Comment by delatbabel** [comment]
I am working on a fix for this but I don't want to submit a PR until my previous PR has been incorporated (otherwise I'll end up with a git branch mess).  I'll see if I can get it working locally before pushing anything.

**Comment by kayladnls** [comment]
Is the other PR that you were talking about #40 ?

**Comment by delatbabel** [comment]
Yes correct.  I will submit another PR today.

**Comment by delatbabel** [comment]
FYI the endpoint that RestUpdateCard points to appears to be having some issues at the PayPal end.  I have submitted a PayPal support question here: https://ppmts.custhelp.com/app/account/questions/detail/i_id/1081166 (not sure if you can see that link or if it's specific to me) and also there is a StackOverflow question here: http://stackoverflow.com/questions/20858910/paypal-rest-api-update-a-stored-credit-card  I will hold off on submitting my PR until these issues are resolved.

**Comment by delatbabel** [comment]
Further to this -- I have an answer from PayPal that the PATCH method is no longer supported, and therefore RestUpdateCard will not work.  I will update the files accordingly and submit the PR to remove this message.
