### ISSUE TITLE
API version update for Express Checkout

### ISSUE THREAD

**Issue by leith** [thephpleague/omnipay-paypal#51]
So, after talking to PayPal today, the latest API version for the Express Checkout is `119.0`. Since the current library is listed as `85.0` with no mechanism for overriding it, I'd like to know what the best foot forward is - is it better to have a look at the [list of changelogs](https://developer.paypal.com/webapps/developer/docs/classic/release-notes/#MerchantAPI) and update the functionality while leaving keyed to a specific API version, or provide a means to set the API version you'd like to call and use the constant as a back up if none is supplied?

**Comment by kayladnls** [comment]
The problem I worry about with setting the API version is that there may be some BC breaks between 85.0 and 119.0 and that would cause the requests to fail or behave differently. 

Are there specific features in 119 that aren't in 85 that you need to use?

**Comment by leith** [comment]
I take it from your response that your preference would be to keep the library statically keyed to a specific API version then?

In addition to the link from before, a colleague pointed out [this list](https://developer.paypal.com/webapps/developer/docs/classic/release-notes/merchant/PayPal_Merchant_API_PreviousVersionsNVP/) of smaller release notes as well, although detail is a bit sparse from 85-91 (highest version not in previous link).

No specific features in 119 that I need (that I'm aware of), just recommendation from PayPal since 85 is quite old at this point. I will follow up with them about BC issues, but from previous discussions and reading through the release notes from the above links, it should just be additional options and error responses.

Short term I'm happy using the version 85 API, but we'll probably want to update at some point and I'm happy to help contribute towards that. :)

**Comment by kayladnls** [comment]
V3 of Omnipay is on the books for release this year. That will include a major release of each of the gateways, and I can bump up the API version at that time. :)

**Comment by leith** [comment]
Sounds good. Anything beta for the V3 to preview the changes?

**Comment by leith** [comment]
Small update, I have been assured that there are no backwards compatibility breaking issues between versions.

**Comment by leith** [comment]
Another small update: after talking to the PayPal tech today, apparently using the latest version of the API is a requirement for Partner integration, so if that's the route anyone wants to head down, they'll need to fork or wait for the next version.

I will probably use a fork in the mean time, but still happy to contribute towards any development towards the official omnipay version.

**Comment by deviarte** [comment]
@kayladnls I do have a quick question, what will be the minimum required PHP version for Omnipay v3?

**Comment by kayladnls** [comment]
@deviarte at least 5.4, possibly 5.5. I'm open to hearing community feedback about which option is best for their use case

**Comment by cfreear** [comment]
I suppose the primary reason to choose 5.5 over 5.4 would be to enable us to use Guzzle >= 6 (and the fact that 5.4 is end of life in about three months!)

**Comment by barryvdh** [comment]
3.0 roadmap: https://github.com/thephpleague/omnipay/issues/274
Perhaps better to continue V3 discussion there?

**Comment by leith** [comment]
V3 discussion certainly better over there.

@kayladnls now that this API version bump has been merged in, will there be a minor or revision release for this gateway?

**Comment by kayladnls** [comment]
Minor version tagged @leith 

I'm going to close this issue in favor of moving to the 3.0 Roadmap.
