### ISSUE TITLE
New Tag needed (2.4.1)

### ISSUE THREAD

**Issue by RyanMcEvoy** [thephpleague/omnipay-paypal#52]
We've being using this for an eCommerce system and come across the same as #39 

We created a new bridge to Omnipay and PayPal Rest in which we added a 'fetchCard' request, when this is used it dumps the return from the API into our root directory as a file named "[]"

This would not be an issue if it wasn't for the fact our customer's addresses and information are publicly accessible.

I have noticed "dev-master" currently holds a fix for this so having it tagged would be a god send.
As this is a live environment we do not want to be using development code on our site.

**Comment by kayladnls** [comment]
Tag made! Sorry for the delay.
