### ISSUE TITLE
Insuficient parameters for the PayPal Items + partial Solution

### ISSUE THREAD

**Issue by kayladnls** [thephpleague/omnipay-paypal#53]
_From @robuedi on March 4, 2015 8:23_

In the PayPal Gateway (omnipay/omnipay/src/omnipay/paypal/messages/ExpressAuthorizeRequest)  is only one parameter for the items.
Currently this parameter looks like this:
        $data['PAYMENTREQUEST_0_DESC'] = $this->getDescription();

In PayPal an items has many others parameters. Other parameters that should be added are:
        $data['L_PAYMENTREQUEST_0_NAME0']      =  $this->getName();
        $data['L_PAYMENTREQUEST_0_AMT0']         = $this->getAmount(); 
        $data['L_PAYMENTREQUEST_0_NUMBER0'] = $this->getNumber(); 
        $data['L_PAYMENTREQUEST_0_QTY0']         = $this->getQuantity(); $
        $data['ITEMAMT']                                               = $this->getDescription(); 

_Copied from original issue: thephpleague/omnipay#240_

**Comment by leith** [comment]
@robuedi, this is already implemented by setting the items on the request. If you build the request you can pass in the items as a parameter, or use `setItems()` with an array of items (this is from Omnipay common).

In Omnipay PayPal [AbstractRequest:294](https://github.com/thephpleague/omnipay-paypal/blob/master/src/Message/AbstractRequest.php#L294), you can see it extracts the data and formats it appropriately if the item data is set.

**Comment by TheSoftwareFarm** [comment]
Thanks for the feedback. It seems that i had an older version that caused the problem.
