### ISSUE TITLE
PayPal client details not refilling (missing parameter) + Solution

### ISSUE THREAD

**Issue by kayladnls** [thephpleague/omnipay-paypal#54]
_From @robuedi on March 4, 2015 8:28_

When sending client details to PaPal (like adress, name) the automatic refill is not happening. This is caused by the missing of two parameters that should be added in the PayPal Gateway (omnipay/omnipay/src/omnipay/paypal/messages/ExpressAuthorizeRequest):
            $data['ADDROVERRIDE'] = 1;

The solution code would look like this:
            if ($card = $this->getCard()) {
                $data['ADDROVERRIDE'] = 1;
                $data['PAYMENTREQUEST_0_SHIPTONAME'] = $card->getName();
               $data['PAYMENTREQUEST_0_SHIPTOSTREET'] = $card->getAddress1();

_Copied from original issue: thephpleague/omnipay#241_

**Comment by leith** [comment]
@robuedi, this already seems to be handled in the latest [ExpressAuthorizeRequest:45](https://github.com/thephpleague/omnipay-paypal/blob/master/src/Message/ExpressAuthorizeRequest.php#L45) for all the shipping details.

**Comment by kayladnls** [comment]
@robuedi, after looking through this, @leith is correct. Are you still having problems?

**Comment by delatbabel** [comment]
Appears to have been resolved already + no response from OP.
