### ISSUE TITLE
Credit Card security information not loading

### ISSUE THREAD

**Issue by TheSoftwareFarm** [thephpleague/omnipay-paypal#59]
I have setted the credit card information in this way:
        $card = new CreditCard(array(
                'firstName'         => $user->first_name,
                'lastName'         => $user->last_name,
                'number'            => Input::get('card_number'),
                'expiryMonth'     => Input::get('expiry_month'),
                'expiryYear'        => Input::get('expiry_year'),
                'cvv'                    => Input::get('cvv'),
                'billingAddress1' => $user->address,
                'billingCity'          => $user->city,
                'billingPostcode'  => $user->zip,
                'billingCountry'    => $user->country_code,
                'billingPhone'      => $user->phone,
                'email'                 => $user->email
            ));
Then i sent them to PayPal_Express gateway. While all the information are sent to PayPal, the 'number', 'expiryMonth', 'expiryYear', 'cvv' values are never sent to PayPal, event if i try to send them manually (like 'number'            => '654656677445654654''). 
Also i always validate the card number using Helper::validateLuhn(Input::get('card_number')), so the card number is valid.

**Comment by kayladnls** [comment]
Before you send it to paypal, can you do a `$card->getNumber();` and see what it returns? Is there an issue there?

**Comment by TheSoftwareFarm** [comment]
It returns my card number, it seem to be working well here. The problem is that after taking the card informations they are not sent to PayPal.

**Comment by kayladnls** [comment]
Do you have a link to a repo, or a more fleshed out example of how you're sending them? Which functions you're using, etc.
