### ISSUE TITLE
Paypal Express checkout - Invalid token

### ISSUE THREAD

**Issue by smanikandan-btech** [thephpleague/omnipay-paypal#6]
I'm doing my own e-commerce website by using CI with omnipay. I'm facing one problem after paypal express checkout is finished like "Invalid token" - error code:10410.
Below is my code.

require 'vendor/autoload.php';
use Omnipay\Omnipay;

$gateway = Omnipay::create('PayPal_Express');
$gateway->setUsername("MY-PAYPAL-PRO-USERNAME");
$gateway->setPassword("MY-PAYPAL-PRO-PASSWORD");
$gateway->setSignature("MY-PAYPAL-PRO-SIGNATURE");
$gateway->setTestMode(true);   // right now i'm using testing environment

$order_id = $this->insert_order(); // i wrote separate method to insert the order items and it will return the order id.

```
 $params = array(
        'amount' => '500',
        'currency' => 'USD',
        'returnUrl' => base_url("checkout/returnBack/$order_id"),
        'cancelUrl' => base_url("checkout/returnBack/$order_id"));

    $response = $gateway->completePurchase($params)->send();

    $data = $response->getData(); // this is the raw response object
    echo '<pre>';
    print_r($data);
    echo '</pre>';die;
```

Following is the error:

Array
(
    [TIMESTAMP] => 2014-03-04T10:41:49Z
    [CORRELATIONID] => 570332778c46c
    [ACK] => Failure
    [VERSION] => 85.0
    [BUILD] => 9917844
    [L_ERRORCODE0] => 10410
    [L_SHORTMESSAGE0] => Invalid token
    [L_LONGMESSAGE0] => Invalid token.
    [L_SEVERITYCODE0] => Error
)

Please help me out for this issue. I'm trying last two days, i'm not getting anything from google. Thanks in advance.

**Comment by DanielHitchen** [comment]
Hi guys,

I've just ran into this problem also - I have a whole shopping cart & payment buttons etc set up using Omnipay with PayPal and everything was working fine - using the PP Sandbox, you get redirected to PayPal, complete the transaction & got redirected back to site without any issues, with a successful payment - but as of yesterday when I last checked, the return is now throwing an error of "Invalid Token" for some reason?

I haven't changed anything in my code from the working version, and I've checked that my Omnipay version is up-to-date also, so whether something has changed on PayPal's end, I don't know - has anyone else ran into this issue lately?

Any advice would be much appreciated.

PS, I've never had to manually pass any "token" previously, either in the ```$params``` or the return URL it all just worked as expected, but now I'm getting the "Invalid token" error.

**Comment by DanielHitchen** [comment]
Hi Guys,

Have now fixed my issue above, the CMS I am using was stripping the query parameters off the returnURL for some strange reason (weird) - anyway, all fixed now, phew! :)

**Comment by kayladnls** [comment]
@DanielHitchen that's great to hear. Thanks for the update!

**Comment by webdeveloperrs** [comment]
[TOKEN] => EC%2d5TG49569J6014153X
    [SUCCESSPAGEREDIRECTREQUESTED] => false
    [TIMESTAMP] => 2018%2d10%2d07T10%3a43%3a14Z
    [CORRELATIONID] => bca0b877c8e9c
    [ACK] => Failure
    [VERSION] => 109%2e0
    [BUILD] => 000000
    [L_ERRORCODE0] => 10413
    [L_SHORTMESSAGE0] => Transaction%20refused%20because%20of%20an%20invalid%20argument%2e%20See%20additional%20error%20messages%20for%20details%2e
    [L_LONGMESSAGE0] => The%20totals%20of%20the%20cart%20item%20amounts%20do%20not%20match%20order%20amounts%2e
    [L_SEVERITYCODE0] => Error
