### ISSUE TITLE
PayPal Plus

### ISSUE THREAD

**Issue by hostianer** [thephpleague/omnipay-paypal#63]
Great Package so far, thanks for your awesome work +1

Will you upgrade the package for PayPal Plus ?

**Comment by kayladnls** [comment]
I'm not familiar with Paypal plus. Isn't that just paypal's credit card campaign? What am I missing.

**Comment by hostianer** [comment]
Ai ... i see PayPal Plus is only available in Germany ..
With PayPal Plus you can also pay with cash in advance.

**Comment by kayladnls** [comment]
Ah, I see. Do you have a link with some info or API docs? I'd at least consider adding it.

**Comment by gharlan** [comment]
Here is the integration guide: https://www.paypalobjects.com/webstatic/de_DE/downloads/PayPal-PLUS-IntegrationGuide.pdf

**Comment by delatbabel** [comment]
A PR for this would be welcome but I don't think anyone has time to code this for you.

**Comment by gharlan** [comment]
Yeah, I do not expect that someone will code this for me! :)
Just gave the link because @kayladnls asked for it.
