### ISSUE TITLE
The merchant country is not supported.

### ISSUE THREAD

**Issue by argb** [thephpleague/omnipay-paypal#64]
When I use 
$gatewayFactory=Omnipay::getFactory();
$gateway=$gatewayFactory->create('PayPal_Pro');
error orcurred: "The merchant country is not supported.",  Does PayPal_Pro means "Website Payments Pro"(https://developer.paypal.com/docs/classic/paypal-payments-pro/integration-guide/WPWebsitePaymentsPro/)
This should be support China,but why this happened?

**Comment by kayladnls** [comment]
http://support.getdpd.com/hc/en-us/articles/202202179-PayPal-Website-Payments-Pro-Merchant-Country-Not-Supported

China is not supported.

**Comment by argb** [comment]
@kayladnls so,I want use paypal in China,I only use paypal_express?
