### ISSUE TITLE
Class '\Omnipay\RestGateway\Gateway' not found

### ISSUE THREAD

**Issue by bazo** [thephpleague/omnipay-paypal#66]
running the code from the example written in RestGateway.php
<?php
$gateway = Omnipay::create('RestGateway');
?>

produces this exception. Update your code or your documentation.

**Comment by barryvdh** [comment]
Should indeed be PayPal_Rest:

	$gateway = Omnipay::create('PayPal_Rest');

Do you want to submit a PR to fix the examples?

**Comment by bazo** [comment]
Maybe when I finish guessing how do you process a payment with this lib

**Comment by barryvdh** [comment]
Ok cool.

Dus you read http://omnipay.thephpleague.com ?
