### ISSUE TITLE
Require Billing Address in Express Checkout

### ISSUE THREAD

**Issue by beaudierman** [thephpleague/omnipay-paypal#74]
I haven't been able to find option to require a billing address for my SetExpressCheckout calls - am I missing it or is this something I could add and send a PR for?

It should be noted that this option needs to be enabled by PayPal for the account, here are the docs: https://www.paypalobjects.com/webstatic/en_US/developer/docs/pdf/limited-release/PP_LRD_BillingAddress.pdf

**Comment by Namek** [comment]
http://stackoverflow.com/questions/18495788/setting-shipping-info-in-omnipay ?

**Comment by beaudierman** [comment]
@Namek That SO question is regarding sending shipping info to PayPal.  My question above is regarding sending the flag to require PayPal to return a billing address.

**Comment by delatbabel** [comment]
If you can implement a PR for this then that would be useful. However for the time being this is not implemented.
