### ISSUE TITLE
How to identify the type used in payment?

### ISSUE THREAD

**Issue by MarlonEtiene** [thephpleague/omnipay-paypal#90]
Hello,
Have anyway to know if user used credit card (and the flag) or another payment type?

Thanks in advance.

**Comment by kayladnls** [comment]
Which gateway are you using? Are you talking about the `fetchTransaction` method, or one of the methods that redirects offsite?

**Comment by MarlonEtiene** [comment]
I am using PayPal_Express and I am developing with Laravel 5.1

I make call to `purchase` method with my API identification, `setTestMode(true)` and my cart itens (name, quantity and price) also I sending grand total (amount) my `returnUrl`, `cancelUrl` and `currency` (BRL)

After `completePurchase` method I got this response
```
array:25 [▼
  "TOKEN" => "EC-7A446779BE983241B"
  "SUCCESSPAGEREDIRECTREQUESTED" => "false"
  "TIMESTAMP" => "2015-10-27T20:48:03Z"
  "CORRELATIONID" => "830c7f178c73b"
  "ACK" => "Success"
  "VERSION" => "85.0"
  "BUILD" => "18308778"
  "INSURANCEOPTIONSELECTED" => "false"
  "SHIPPINGOPTIONISDEFAULT" => "false"
  "PAYMENTINFO_0_TRANSACTIONID" => "6UK29018514468133"
  "PAYMENTINFO_0_TRANSACTIONTYPE" => "cart"
  "PAYMENTINFO_0_PAYMENTTYPE" => "instant"
  "PAYMENTINFO_0_ORDERTIME" => "2015-10-27T20:48:02Z"
  "PAYMENTINFO_0_AMT" => "450.00"
  "PAYMENTINFO_0_FEEAMT" => "15.70"
  "PAYMENTINFO_0_TAXAMT" => "0.00"
  "PAYMENTINFO_0_CURRENCYCODE" => "BRL"
  "PAYMENTINFO_0_PAYMENTSTATUS" => "Completed"
  "PAYMENTINFO_0_PENDINGREASON" => "None"
  "PAYMENTINFO_0_REASONCODE" => "None"
  "PAYMENTINFO_0_PROTECTIONELIGIBILITY" => "Eligible"
  "PAYMENTINFO_0_PROTECTIONELIGIBILITYTYPE" => "ItemNotReceivedEligible,UnauthorizedPaymentEligible"
  "PAYMENTINFO_0_SECUREMERCHANTACCOUNTID" => "V99F7XQ8RVT44"
  "PAYMENTINFO_0_ERRORCODE" => "0"
  "PAYMENTINFO_0_ACK" => "Success"
]
```
I not used this `fetchTransaction` method I need it? If yes where I need to call it?

**Comment by delatbabel** [comment]
Hi,

I don't believe that it's possible to find the payment type that the customer used or any other details (card number, etc). I believe that PayPal deliberately do not disclose that information.

I don't think that it's required to call fetchTransaction, it will just give you back much the same information that you got in the purchase() call data.

**Comment by MarlonEtiene** [comment]
@delatbabel thank you for your answer.
I think you are right Paypal don't give this informations.
