### ISSUE TITLE
function setLocaleCode()

### ISSUE THREAD

**Issue by Zonork** [thephpleague/omnipay-paypal#98]
Hi.
I need set the language of my payment gateway to english, i see a mention in an issue of the "setLocaleCode()" function, but how i can use that function?

thanks

**Comment by Zonork** [comment]
i solve this problem, re-implementing the function:

    public function setLocaleCode($value)
    {
        return $this->setParameter('localeCode', $value);
    }

in ExpressGateway.php,

i don't know if that is the better way to do that, for that i left this issue open.

**Comment by leith** [comment]
You don't need to set this on the gateway, just the request - which is why it's a part of the `Omnipay\PayPal\Message\AbstractRequest` class. When you're creating a request object, you can just set the localeCode as a part of the set of parameters that you give it.

**Comment by delatbabel** [comment]
If you wish you can submit a PR for this, but as leith noted it should be on the AbstractRequest class not on the Gateway class.
